name: Auto PR, Build and Deploy

on:
  push:
    branches: [ "master" ] 

jobs:
  create-pr-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git remote add upstream https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/BryCris15/digitalocean-service.git
          
          git fetch --all
          
          echo "=== RAMAS REMOTAS ==="
          git branch -r
          
          if ! git show-ref --quiet refs/remotes/upstream/master; then
            echo "::error::No se encontró upstream/master"
            exit 1
          fi

      - name: Create Pull Request
        id: pr-creator
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: "autoupdate-${{ github.run_id }}" 
          base: master
          title: "Actualización automática - $(date +'%d/%m/%Y')"
          body: |
            :robot: **Actualización automática** :arrows_counterclockwise:
            
            - **Commit:** [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            - **Imagen Docker:** stevxd97/digital_ocean:${{ github.sha }}
            - **Ejecución:** [#${{ github.run_number }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          labels: "automated,ci"
          commit-message: "chore: auto-update from fork"
          delete-branch: true 

      - name: Show PR Creation Status
        if: steps.pr-creator.outputs.result != 'success'
        run: |
          echo "::error::No se creó el PR. Motivo: ${{ steps.pr-creator.outputs.result }}"
          echo "=== DIFF CON UPSTREAM ==="
          git diff origin/main..upstream/master --stat
          echo "=== ÚLTIMOS COMMITS ==="
          git log --oneline -n 5 origin/main
          git log --oneline -n 5 upstream/master
          exit 1
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t stevxd97/digital_ocean:latest .
          docker tag stevxd97/digital_ocean:latest stevxd97/digital_ocean:${{ github.sha }}
          docker push stevxd97/digital_ocean:latest
          docker push stevxd97/digital_ocean:${{ github.sha }}
