name: Auto PR, Build and Deploy

on:
  push:
    branches: [ "master" ]  # Cambiado a master para ambos repos

jobs:
  create-pr-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Paso 1: Checkout del código
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Paso 2: Configurar Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add upstream https://github.com/BryCris15/digitalocean-service.git
          git fetch upstream master

      # Paso 3: Crear Pull Request
      - name: Open Pull Request
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          from-branch: "master"  # Tu rama (en tu fork)
          to-branch: "master"    # Rama en BryCris15/digitalocean-service
          repository-owner: "BryCris15"
          repository: "digitalocean-service"
          pr-title: "Actualización automática - $(date +'%Y-%m-%d')"
          pr-body: "Actualización automática desde fork. Commit: ${{ github.sha }}"

      # Paso 4: Docker Build & Push
      - name: Build and Push Docker Image
        run: |
          docker build -t stevxd97/digital_ocean:latest .
          docker tag stevxd97/digital_ocean:latest stevxd97/digital_ocean:${{ github.sha }}
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push stevxd97/digital_ocean:latest
          docker push stevxd97/digital_ocean:${{ github.sha }}
