on:
  push:
    branches: [ "master" ]

jobs:
  create-pr-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Paso 1: Checkout con todas las ramas
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      # Paso 2: Configurar Git y crear rama temporal
      - name: Prepare Git Environment
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Crear rama temporal con cambios
          git checkout -b auto-update-${{ github.run_id }}
          
          # Hacer commit (simulando cambios)
          touch update-$(date +%s).txt
          git add .
          git commit -m "Auto-update: ${{ github.sha }}"

      # Paso 3: Crear Pull Request
      - name: Open Pull Request
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          from-branch: "auto-update-${{ github.run_id }}"  # Rama temporal
          to-branch: "master"  # Rama destino
          repository-owner: "BryCris15"
          repository: "digitalocean-service"

      # Paso 4: Docker Build & Push
      - name: Build and Push Docker Image
        run: |
          docker build -t stevxd97/digital_ocean:latest .
          docker tag stevxd97/digital_ocean:latest stevxd97/digital_ocean:${{ github.sha }}
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push stevxd97/digital_ocean:latest
          docker push stevxd97/digital_ocean:${{ github.sha }}
