name: Auto PR, Build and Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  create-pr-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Setup Git Environment
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Configurar upstream
          git remote add upstream https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/BryCris15/digitalocean-service.git
          
          # Fetch completo
          git fetch --all
          
          # Debug: Ver ramas
          echo "=== RAMAS ==="
          git branch -av

      - name: Check for changes
        id: check-changes
        run: |
          # Comparación directa
          if [ -z "$(git diff master upstream/master --shortstat)" ]; then
            echo "::warning::No hay cambios entre tu master y upstream/master"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "::notice::Cambios detectados!"
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "=== DIFF ==="
            git diff master upstream/master --stat
          fi

      - name: Create Pull Request
        if: steps.check-changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: "auto-update-${{ github.run_number }}" 
          base: master  
          title: "Actualización automática - ${{ github.run_number }}"
          body: |

            - **Origen:** [${{ github.repository }}@${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            - **Diferencias:**
            ```diff
            ${{ steps.check-changes.outputs.diff }}
            ```
          labels: "automated"
          commit-message: "Auto-update: ${{ github.run_number }} [skip ci]"
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t stevxd97/digital_ocean:latest .
          docker tag stevxd97/digital_ocean:latest stevxd97/digital_ocean:${{ github.sha }}
          docker push stevxd97/digital_ocean:latest
          docker push stevxd97/digital_ocean:${{ github.sha }}
