name: Auto PR, Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  create-pr-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add upstream https://github.com/${{ secrets.UPSTREAM_REPO }}.git
          git fetch upstream

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          head: ${{ github.repository_owner }}:main
          base: main 
          repo: ${{ secrets.UPSTREAM_REPO }}
          title: "Auto PR: Actualización desde fork"
          body: "Actualización automática desde fork. Docker image: stevxd97/digital_ocean:${{ github.sha }}"
          labels: "automated"
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t stevxd97/digital_ocean:latest .
          docker tag stevxd97/digital_ocean:latest stevxd97/digital_ocean:${{ github.sha }}
          docker push stevxd97/digital_ocean:latest
          docker push stevxd97/digital_ocean:${{ github.sha }}
